apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
type: Opaque
stringData:
  GITHUB_APP_APP_ID: $VAULT_GITHUB_OVERLAYS_APP_ID
  GITHUB_APP_CLIENT_ID: $VAULT_GITHUB_OVERLAYS_APP_CLIENT_ID
  GITHUB_APP_CLIENT_SECRET: $VAULT_GITHUB_OVERLAYS_APP_CLIENT_SECRET
  GITHUB_APP_PRIVATE_KEY: "${VAULT_GITHUB_OVERLAYS_APP_PRIVATE_KEY}"
  GITHUB_APP_WEBHOOK_URL: $VAULT_GITHUB_OVERLAYS_APP_WEBHOOK_SECRET
  GITHUB_APP_WEBHOOK_SECRET: $VAULT_GITHUB_OVERLAYS_APP_WEBHOOK_URL
  GITHUB_OAUTH_APP_ID: $VAULT_GITHUB_OAUTH_OVERLAYS_APP_ID
  GITHUB_OAUTH_APP_SECRET: $VAULT_GITHUB_OAUTH_OVERLAYS_APP_SECRET
  GITHUB_ORG: $VAULT_GITHUB_ORG
  GITHUB_URL: https://github.com
  GH_USER_ID: $VAULT_GH_USER_ID
  GH_USER_PASS: $VAULT_GH_USER_PASS
  GH_2FA_SECRET: $VAULT_GH_2FA_SECRET
  GH_RHDH_QE_USER_TOKEN: $VAULT_GITHUB_USER_TOKEN
